[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "seizure_detection"
version = "0.0.1"
description = "A classification project for the detection of epileptic seizure episodes using EEG data (Bangalore EEG Epilepsy Dataset)."
authors = [
  { name = "Cameron Cochrane" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.12.0"


[tool.ruff]
line-length = 99
src = ["seizure_detection"]
include = ["pyproject.toml", "seizure_detection/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["seizure_detection"]
force-sort-within-sections = true

